language: ruby
script: bundle exec rake rspec
rvm:
  - 2.1.4
  - 2.0.0
  - 1.9.3
notifications:
  email:
    - aalsum@stanford.edu
before_script:
  - cp config/targets/example.yml config/targets/test.yml
  - cp config/environments/example.rb config/environments/test.rb
  - "bundle exec rake db:migrate"
