# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f97ebe9f95ae61e7b375dec69fbb2466a531935e73ea1aa49eb463b8d29b842383bbd07762d7c9dd4bae7eae240b281d6fb9f2fbd56d31465067c2ab36ea33b5

test:
  secret_key_base: 64ad3de89d672e8f833c3ce9de7de70d8d0d12bbcc4fe1e05da99000cd8c7da1fe9ff8e56a6c587769e5b91ffc1a831b9f70b602647811ec662c0d6215d7e341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
